# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: Dockerhub
- name: imageName_api
  value: 'mtgscores2_api:ci-$(build.buildId)'
- name: imageName_api_latest
  value: 'mtgscores2_api:latest'
- name: imageName_api_build
  value: 'mtgscores2_api_build:ci-$(build.buildId)'
- name: imageName_web
  value: 'mtgscores2_web:ci-$(build.buildId)'
- name: imageName_web_latest
  value: 'mtgscores2_web:latest'
- name: imageName_identityserver
  value: 'mtgscores2_identityserver:ci-$(build.buildId)'
- name: imageName_identityserver_latest
  value: 'mtgscores2_identityserver:latest'

steps:
- script: |
    docker build -f src/api/ci.build.yml -t $(imageName_api_build) src/api/
    docker run --name api_build --rm -d -t $(imageName_api_build)
    docker cp api_build:/app/MTG.Scores2.Api.Tests/TestResults/testresults.trx $(System.DefaultWorkingDirectory)
    docker cp api_build:/out $(System.DefaultWorkingDirectory)/src/api
    docker stop api_build
  displayName: 'docker build api'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

- script: |
    docker build -f src/api/ci.runtime.yml -t $(dockerhub_user)/$(imageName_api) -t $(dockerhub_user)/$(imageName_api_latest) src/api/
  displayName: 'docker build runtime image api'

- script: |
    docker build -f src/web/Dockerfile -t $(dockerhub_user)/$(imageName_web) -t $(dockerhub_user)/$(imageName_web_latest) src/web/
  displayName: 'docker build web image'

- script: |
    docker build -f src/identityserver/Dockerfile -t $(dockerhub_user)/$(imageName_identityserver) -t $(dockerhub_user)/$(imageName_identityserver_latest) src/identityserver
  displayName: 'docker build identityserver image'

- task: Docker@1
  inputs:
    dockerRegistryEndpoint: 'wpelczar_dockerhub'
    containerregistrytype: 'Container Registry'
    command: login
  displayName: 'dockerhub login'

- script: |
    docker push $(dockerhub_user)/$(imageName_api)
    docker push $(dockerhub_user)/$(imageName_api_latest)
  displayName: 'push api image to dockerhub'
  
- script: |
    docker push $(dockerhub_user)/$(imageName_web)
    docker push $(dockerhub_user)/$(imageName_web_latest)
  displayName: 'push api image to dockerhub'

  
- script: |
    docker push $(dockerhub_user)/$(imageName_identityserver)
    docker push $(dockerhub_user)/$(imageName_identityserver_latest)
  displayName: 'push identityserver image to dockerhub'