version: '3.3'
services:
  api:
    build: 
      context: ./
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      - db
    networks:
      - app-net
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Your_password123", "-Q", "select 1" ]
      interval: 5s
      retries: 20
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - app-net
  web:
    build: 
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-net

networks:
  app-net:

volumes:
  sqlvolume: