version: '2.1'
services:
    api:
        build: src/MTG.Scores2.Api/.
        ports:
            - "5000:80"
        depends_on:
            db:
             condition: service_healthy
 
    db:
        build: 
          context: Database/.
        ports: 
          - "1433:1433"
        healthcheck:
            test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Your_password123", "-Q", "select 1" ]
            interval: 5s
            retries: 20
        volumes:
            - "c:/mssqldata:C:/mssqldata"