version: '2.1'
services:
  api:
    build: 
      context: ./
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net
  db:
    build: 
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports: 
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Your_password123", "-Q", "select 1" ]
      interval: 5s
      retries: 20
    volumes:
      - "c:/mssqldata:C:/mssqldata"
    networks:
      - app-net
  web:
    build: 
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-net

networks:
  app-net: